"""initial schema

Revision ID: 004c6e739318
Revises: 
Create Date: 2026-10-05 19:30:46.902538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004c6e739318'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("exchange IN ('kucoin','bybit')", name='ck_coins_exchange'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('idx_coins_symbol', 'coins', ['symbol'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_role', 'users', ['role_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ema_period', sa.Integer(), nullable=False),
    sa.Column('target_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stop_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('bollinger_period', sa.Integer(), nullable=False),
    sa.Column('bollinger_std', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.CheckConstraint('bollinger_period > 0', name='ck_settings_boll_period'),
    sa.CheckConstraint('bollinger_std > 0', name='ck_settings_boll_std'),
    sa.CheckConstraint('check_interval > 0', name='ck_settings_check'),
    sa.CheckConstraint('ema_period > 0', name='ck_settings_ema'),
    sa.CheckConstraint('stop_pct > 0', name='ck_settings_stop'),
    sa.CheckConstraint('target_pct > 0', name='ck_settings_target'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'coin_id', name='uq_user_coin')
    )
    op.create_index('idx_user_coins_coin', 'user_coins', ['coin_id'], unique=False)
    op.create_index('idx_user_coins_user', 'user_coins', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usercoin_id', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('profit_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('exit_type', sa.String(length=10), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.CheckConstraint("exit_type IN ('TARGET','STOP','MANUAL')", name='ck_positions_exit_type'),
    sa.ForeignKeyConstraint(['usercoin_id'], ['user_coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_usercoin', 'positions', ['usercoin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_positions_usercoin', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_user_coins_user', table_name='user_coins')
    op.drop_index('idx_user_coins_coin', table_name='user_coins')
    op.drop_table('user_coins')
    op.drop_table('settings')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('idx_coins_symbol', table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###
